name       : perl-io-html
version    : 1.001
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/C/CJ/CJM/IO-HTML-1.001.tar.gz : ea78d2d743794adc028bc9589538eb867174b4e165d7d8b5f63486e6b828e7e0
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : IO::HTML - Open an HTML file with automatic charset detection
description: |
    This module opens a file and performs automatic charset detection based on the HTML5 algorithm.  You can then pass the filehandle to HTML::Parser or a related module (or just read it yourself).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
