name       : perl-io-html
version    : '1.004'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/C/CJ/CJM/IO-HTML-1.004.tar.gz : c87b2df59463bbf2c39596773dfb5c03bde0f7e1051af339f963f58c1cbd8bf5
homepage   : https://metacpan.org/pod/IO::HTML
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : IO::HTML - Open an HTML file with automatic charset detection
description: |
    This module opens a file and performs automatic charset detection based on the HTML5 algorithm. You can then pass the filehandle to HTML::Parser or a related module (or just read it yourself).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
